[pylama]
linters = pylint,pycodestyle,pyflakes

[pylama:pycodestyle]
ignore=
# Line too long
	E501,

[pylama:pyflakes]

[pylama:pylint]
disable=
#		arguments-differ,
#		attribute-defined-outside-init,
#		broad-exception-caught,
#		broad-exception-raised,
#		cell-var-from-loop,
#		consider-using-f-string,
#		dangerous-default-value,
#		import-outside-toplevel,
#		inconsistent-return-statements,
#		invalid-name,
#		line-too-long,
#		method-cache-max-size-none,
#		missing-class-docstring,
#		missing-function-docstring,
#		missing-module-docstring,
#		no-else-break,
#		no-else-continue,
#		no-else-raise,
#		no-else-return,
#		pointless-string-statement,
#		protected-access,
#		redefined-argument-from-local,
#		redefined-builtin,
#		redefined-outer-name,
#		single-string-used-for-slots,
#		suppressed-message,
#		too-few-public-methods,
#		too-many-ancestors,
#		too-many-arguments,
#		too-many-boolean-expressions,
#		too-many-branches,
#		too-many-instance-attributes,
#		too-many-lines,
#		too-many-locals,
#		too-many-nested-blocks,
#		too-many-public-methods,
#		too-many-return-statements,
#		too-many-statements,
#		unused-argument,
#		unused-variable,
#		used-before-assignment,
#		wrong-import-order,
good-names=i,j,k,ex,Run,_,ok

# Allow modules to be named in either snake_case or kebab-case, since the
# latter is often used for executable scripts.
# module_rgx=(?:(?:[^\W\dA-Z][^\WA-Z]*)|(?:[^\W\dA-Z](?:[^\WA-Z_]|-)*))$

# Some classes have dynamically generated members.
# generated-members=CiA402Dict.*.*
